version: '3'

services:
  app:
    build: .  # Используем Dockerfile в корне
    container_name: flask_bot_app
    ports:
      - "5000:5000"  # Прокидываем порт Flask-админки
    restart: always  # Автоматический перезапуск при сбое
    volumes:
      - ./data:/app/data
